import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Spec-Kit Documentation',
      collapsed: false,
      items: [
        'spec-kit/intro',
        'spec-kit/using-speckit',
        'spec-kit/constitution',
        'spec-kit/specifications',
        'spec-kit/implementation-plan',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1',
        },
        {
          type: 'autogenerated',
          dirName: 'module-2',
        },
        {
          type: 'autogenerated',
          dirName: 'module-3',
        },
        {
          type: 'autogenerated',
          dirName: 'module-4',
        },
      ],
    },
    'hardware',
    'setup',
    'faq',
  ],
};

export default sidebars;
